version: '3.8'

services:
  app_dev:
    build:
      dockerfile: .docker/images/app/Dockerfile
      context: .
    env_file:
      - .docker/local.env
      - .env
    command: /start-reload.sh # Only for development. Reloads Gunicorn when source changes.
    healthcheck:
      disable: true # Disable healthcheck for local development.
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app:ro"
      - "./tests:/tests:rw"  # give read-write permission to write junitxml test reports here.
      - "./tmp:/tmp:rw"  # give permission to export the GraphQL schema here.
      - "./.docker:/.docker:ro"  # Functional Tests read files from .docker/localstack/dynamodb.
    depends_on:
      - localstack
      - memcached
      - snowplow

  localstack:
    image: localstack/localstack:0.12.11
    env_file:
      - .docker/local.env
    ports:
      - '4566-4599:4566-4599'
      - '8080:8080'
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - DEBUG=1
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EXTRA_CORS_ALLOWED_HEADERS=Content-Disposition, Content-Type, x-amz-acl
      - EXTRA_CORS_EXPOSE_HEADERS=ETag
      - HOSTNAME_EXTERNAL=localstack

  memcached:
    image: library/memcached:1.6
    ports:
      - '11211:11211'

  snowplow:
    image: pocket/snowplow-micro:latest
    platform: linux/amd64
    ports:
      - '9090:9090'



#qdrant:
# image: qdrant/qdrant:v0.10.2
# ports:
#     - 6333:6333
# volumes:
#     - /tmp/qdrant:/qdrant/storage
