# This config connects with the Pocket-Dev environment for local development.

version: '3.8'

services:
  app_dev:
    build:
      dockerfile: .docker/images/app/Dockerfile
      context: .
    env_file:
      - .docker/local-dev.env
      - .env
    environment:
      - OTEL_SERVICE_NAME=RecommendationAPI
    command: /start-reload.sh # Only for development. Reloads Gunicorn when source changes.
    healthcheck:
      disable: true # Disable healthcheck for local development.
    ports:
      - "8000:8000"
    volumes:
      - "~/.aws:/home/appuser/.aws:ro"
      - "./app:/app:ro"
      - "./app:/opt/project/src:ro" # PyCharm overrides app to /opt/project/src
    depends_on:
      - aws-ot-collector

  # AWS Distro for OpenTelemetry (ADOT) Collector for sending traces to AWS X-Ray
  aws-ot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    env_file:
      - .docker/local-dev.env
      - .env
    volumes:
      - "./.docker/aws-ot-collector/local-development.yaml:/etc/otel-agent-config.yaml"
      - "~/.aws:/root/.aws"
    ports:
      - "4317:4317"   # grcp port for receiving spans
      - "55681:55681" # http port for receiving spans
      - "13133"       # health_check
