# This config connects with the Pocket-Dev environment for local development.

version: '3.8'

services:
  app_dev:
    build:
      dockerfile: .docker/images/app/Dockerfile
      context: .
    env_file:
      - .docker/local-dev.env
      - .env
    command: /start-reload.sh # Only for development. Reloads Gunicorn when source changes.
    healthcheck:
      disable: true # Disable healthcheck for local development.
    ports:
      - "8000:8000"
    volumes:
      - "~/.aws:/home/appuser/.aws:ro"
      - "./app:/app:ro"
      - "./app:/opt/project/src:ro" # PyCharm overrides app to /opt/project/src
    depends_on:
      - xray_daemon

  xray_daemon:
    image: amazon/aws-xray-daemon
    command:
      - '--region'
      - 'us-east-1'
      - '--local-mode'
    environment:
      # Run `source <(maws -o awscli)` to export credentials with AWS CLI
      - AWS_PROFILE=pocket-dev-PocketSSODataLearning
    ports:
      - '2000:2000/udp'
      - '2000:2000/tcp'
    volumes:
      - "~/.aws:/home/root/.aws:ro"
