from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field

from app.models.corpus_item_model import CorpusItemModel
from app.models.recommendation_reason_model import RecommendationReasonModel


class CorpusRecommendationModel(BaseModel):
    id: str = Field(
        default_factory=lambda: str(uuid4()),
        description='A unique identifier for this specific recommendation across all recommendations. '
                    'This identifier is generated by the a machine learning system making recommendation decisions. '
                    'This field can be joined with recommendation decisions to aggregate more meta data about the '
                    'decision.')

    corpus_item: Optional[CorpusItemModel] = Field(description='Content meta data.')

    reason: Optional[RecommendationReasonModel] = Field(
        description='Reason why this CorpusItem is recommended to the user, or null if no reason is available.')
